# Site settings
title: Rad Posts Things
email: spamprevention@askmeforthisviasomethingelse.com
description: > # this means to ignore newlines until "baseurl:"
  All posts here are the personal thoughts / opinions of
  Zakary French, and do not reflect those of his employer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://radruler.github.io/" # the base hostname & protocol for your site
twitter_username: radruler
github_username:  radruler

# Build settings
markdown: kramdown
show_drafts: true
